### ISSUE TITLE
Segfault at execution of oce_adv_tra_fct_opt1

### ISSUE THREAD

**Issue by juliegaspar** [ESiWACE-S1/fesom2-kernels#3]
### Issue

While testing this benchmark, we came across a segmentation fault at the execution of oce_adv_tra_fct_opt1 compiled with ifx version 22.0.0 on Intel Xeon Gold 6254. It occurs for each set of the provided input data. Note that for ifort or gfortran I do not have this issue.

### Building
Here is the procedure to re-create the issue.

```
$ cmake . -DCMAKE_Fortran_COMPILER:FILEPATH=/path/to/ifx -DCMAKE_Fortran_FLAGS:STRING="-O3 -march=skylake-avx512 -g"
$ make
$ cd inputs/cores2
$ ../../oce_adv_tra_fct_opt1
```

### Error
Here is the error ouput.

```
loading      126858  node levels
loading      244659  element nodes
loading      244659  element levels
loading      126858  node elems
loading      371644  edge nodes
loading      371644  edge levels
loading      371644  edge tri
DEFAULT: iterating over         200  iterations...
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
oce_adv_tra_fct_o  0000000000411CBA  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FCD0ADA1630  Unknown               Unknown  Unknown
oce_adv_tra_fct_o  0000000000406D00  Unknown               Unknown  Unknown
oce_adv_tra_fct_o  00000000004049A2  Unknown               Unknown  Unknown
libc-2.17.so       00007FCD0A9E6555  __libc_start_main     Unknown  Unknown
oce_adv_tra_fct_o  00000000004048A9  Unknown               Unknown  Unknown
```

After some research, the problem seems to manifest at line 98 of oce_adv_tra_fct_opt1.F90.

Julie Gaspar
SW Benchmark Intern
[julie.gaspar@sipearl.com](mailto:julie.gaspar@sipearl.com)

**Comment by juliegaspar** [comment]
### Issue solution
The issue comes from the variable « nl » that is not initialized. As seen in the original code of FESOM, adding the following line (after line 75 for exemple) , fixes the segmentation fault :

`nl=maxval(nlevels(:)) `

Julie Gaspar
SW Benchmark Intern
[julie.gaspar@sipearl.com](mailto:julie.gaspar@sipearl.com)

**Comment by dguibert** [comment]
Hi @juliegaspar,

Thanks for this issue. I reopen it until a Pull Request will be open to solve this.
